name: Run Tests

on:
  push:
    branches:
      - testing-for-exam
  pull_request:
    branches:
      - testing-for-exam

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: cibot
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD: ""
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and start containers
        run: docker-compose -f .docker-compose.yml up -d

      - name: Wait for MySQL to be ready
        run: |
          until docker exec $(docker-compose ps -q db) mysqladmin ping --silent; do
            echo 'Waiting for MySQL...'
            sleep 5
          done

      - name: Run migrations and tests
        run: |
          docker-compose exec app php artisan migrate --force
          docker-compose exec app php artisan test

      - name: Stop containers
        if: always()
        run: docker-compose down