name: Run Tests

on:
  push:
    branches:
      - '**' # Cette ligne permet de déclencher le workflow sur toutes les branches
  pull_request:
    branches:
      - '**' # Cette ligne permet de déclencher le workflow pour tous les pull requests sur toutes les branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Remplacez par la version de PHP utilisée dans votre projet
          extensions: mbstring, xml, ctype, json, bcmath, tokenizer, zip, mysqli, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
